### ISSUE TITLE
Connection lost when downloading new image

### ISSUE THREAD

**Issue by bastien-phi** [tpetry/stackbricks-community#27]
The error occurred in beta Linux AppImage

If internet connection is lost when a new docker image is downloaded, we finally get 
```
Unhandled Error
TypeError: Cannot read properties of undefined (reading 'match')
    at /tmp/.mount_StackBJgOARH/resources/app/packages/main/dist/index.cjs:31:77
    at /tmp/.mount_StackBJgOARH/resources/app/packages/main/dist/index.cjs:30:43095
    at Array.find (<anonymous>)
    at Object.v [as run] (/tmp/.mount_StackBJgOARH/resources/app/packages/main/dist/index.cjs:30:43078)
    at Object.otherwise (/tmp/.mount_StackBJgOARH/resources/app/packages/main/dist/index.cjs:30:43725)
    at IncomingMessage.<anonymous> (/tmp/.mount_StackBJgOARH/resources/app/packages/main/dist/index.cjs:31:146)
    at IncomingMessage.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at IncomingMessage.Readable.push (node:internal/streams/readable:228:10)
```
Then, the database stays in "Creating" state with the loader loading.

**Comment by tpetry** [comment]
The bug was not due to a lost connection (checked it several times) but that the container did not start correctly. There are many cases why this could happen. But I've fixed the workflow to not crash anymore with an unknown error message. 

Shipped with release `0.7.0`
