### ISSUE TITLE
Cant start Database. Conflict with orbstack?

### ISSUE THREAD

**Issue by pintend** [tpetry/stackbricks-community#30]
```
Unhandled Promise Rejection
NonError: "Can't connect to database"
    at module.exports (/Applications/StackBricks.app/Contents/Resources/app/node_modules/ensure-error/index.js:14:10)
    at handleError (/Applications/StackBricks.app/Contents/Resources/app/node_modules/electron-unhandled/index.js:24:10)
    at process.<anonymous> (/Applications/StackBricks.app/Contents/Resources/app/node_modules/electron-unhandled/index.js:103:4)
    at process.emit (node:events:394:28)
    at emit (node:internal/process/promises:136:22)
    at processPromiseRejections (node:internal/process/promises:237:9)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
```

**Comment by tpetry** [comment]
Honestly, I don't know why it doesn't work. But I've released 0.9.1 to catch that error and no longer display an `Unhandled Promise Rejection` error.

What database did you start? When that message pops up: Can you check from the terminal whether the container is running? Can you connect to it?
