### ISSUE TITLE
Redis - unhandled promise rejection

### ISSUE THREAD

**Issue by Morten010** [tpetry/stackbricks-community#34]
I am getting this error trying to copy my redis database connection url

````
Unhandled Promise Rejection
TypeError: Cannot read properties of null (reading 'split')
    at Za.getConnectionUrl (C:/Users/Itism/AppData/Local/Programs/StackBricks/resources/app/packages/main/dist/index.cjs:47:56210)
    at click (C:/Users/Itism/AppData/Local/Programs/StackBricks/resources/app/packages/main/dist/index.cjs:9:101539)
    at MenuItem.click (node:electron/js2c/browser_init:73:1908)
    at Object.a._executeCommand (node:electron/js2c/browser_init:81:2453)
```

**Comment by tpetry** [comment]
This has been fixed now with release `0.9.2` 😉

StackBricks will nag you to upgrade when you start it again.
