### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by tm69** [tpetry/stackbricks-community#35]
when I try to create a new MySql 8.4.0 and 8.4.x database, stackbricks send this message

`TypeError: Cannot read properties of null (reading 'on')
    at Modem.demuxStream (C:/Users/.../AppData/Local/Programs/StackBricks/resources/app/node_modules/docker-modem/lib/modem.js:398:10)
    at Object.callback (C:/Users/.../AppData/Local/Programs/StackBricks/resources/app/packages/main/dist/index.cjs:30:57653)
    at C:/Users/.../AppData/Local/Programs/StackBricks/resources/app/node_modules/dockerode/lib/container.js:766:12
    at C:/Users/.../AppData/Local/Programs/StackBricks/resources/app/node_modules/docker-modem/lib/modem.js:332:7
    at IncomingMessage.<anonymous> (C:/Users/.../AppData/Local/Programs/StackBricks/resources/app/node_modules/docker-modem/lib/modem.js:351:9)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)`

and in the second time only gets cannot connect to database

docker pull the image, stackbricks create the volume but can't create the container

Windows 11 Pro 23H2
WSL 2
Docker Engine v26.1.4
Stackbricks 0.9.2

**Comment by tpetry** [comment]
That's weird. Tried it again and its working for me.

**Comment by tpetry** [comment]
No you're right. I don't get the error but can't connect to the database either. I'll be looking at the issue. But most probably its an issue with the docker image.

**Comment by tpetry** [comment]
Fixed with release `0.9.3`
